#!/bin/bash
set -e
set -o xtrace

export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1

source .env

(
    LAST_VERSION=$(cat .last_build)

    if [ ! -z "$1" ]; then
        export TAG="$1"
    else
        # $ cargo install semver-cli
        TAG=$(semver-cli "$LAST_VERSION" --increment)
        export TAG
    fi

    if [ ! -z "$2" ]; then
        export MESSAGE="$2"
        git add .
    fi

    docker-compose -f docker-compose.build.yml build --pull #--parallel
    docker-compose -f docker-compose.build.yml push

    if [ ! -z "$MESSAGE" ]; then
        git commit -m "$2"
        git tag "$PROJECT-$TAG"
    fi

    echo "$TAG" >.last_build
    sed -i "s/version: ${LAST_VERSION}/version: ${TAG}/g" charts/login/values.yaml
    sed -i "s/${LAST_VERSION}/${TAG}/g" charts/login/Chart.yaml
)
