---
services:
  gateway:
    build: login/gateway
    image: "${REGISTRY}/${PROJECT}/gateway:${TAG}"
  login:
    build: login/login
    image: "${REGISTRY}/${PROJECT}/login:${TAG}"
  wrapper:
    build: login/wrapper
    image: "${REGISTRY}/${PROJECT}/wrapper:${TAG}"
version: "3.7"
