apiVersion: v1
appVersion: "1.0"
description: Cryptoverse Login
name: cryptoverse-login
version: 1.3.0
dependencies:
  - name: hydra
    version: 0.21.5
    repository: "https://k8s.ory.sh/helm/charts"
