sentryDSN: ""
sentryEnv: "ci"
domain: login.cryptoverse.local

ingressClassName: public

imagePullSecrets:
  - name: registry-cryptoverse

hydra:
  hydra:
    dangerousForceHttp: true
    config:
      dsn: "memory"
      urls:
        login: https://login.cryptoverse.local/login
        consent: https://login.cryptoverse.local/consent
        self:
          issuer: https://login.cryptoverse.local/
      secrets:
        cookie:
          - localsecretttttt # pragma: allowlist secret
        system:
          - localsecretttttt # pragma: allowlist secret

djangoSecrets: "localsecret" # pragma: allowlist secret

introspectAccess:
  user: "localuser" # pragma: allowlist secret
  pass: "$5$8kkgRZ7KA7$wYpOtm2YBFDcp.uP8nKMcp1Y9BInU.T9GMpUer.hUE." # pragma: allowlist secret

monitoring:
  enabled: false

debug: true
