apiVersion: v1
kind: Secret
metadata:
  name: {{ include "login.fullname" . }}-hydra
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "login.labels" . | indent 4 }}
stringData:
  secretsSystem: {{ .Values.secretsSystem }}
  secretsCookie: {{ .Values.secretsCookie }}
