apiVersion: v1
kind: Secret
metadata:
  name: {{ include "login.fullname" . }}-register
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "login.labels" . | indent 4 }}
stringData:
  django: {{ .Values.djangoSecrets }}
