apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "login.fullname" . }}-register
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "login.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.register.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "login.fullname" . }}-register
  template:
    metadata:
      labels:
        app: {{ include "login.fullname" . }}-register
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - env:
            - name: DOMAIN
              value: {{ .Values.domain }}
            - name: PORT
              value: {{ .Values.register.deployment.port | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.registry }}/{{ .Values.register.image.repository }}:{{ .Values.version }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: register
          resources: {}
          volumeMounts:
            - mountPath: /app/secrets
              name: secrets
          ports:
            - name: http
              containerPort: {{ .Values.register.deployment.port }}
      restartPolicy: Always
      volumes:
        - name: secrets
          secret:
            secretName: {{ include "login.fullname" . }}-register
