apiVersion: v1
kind: Service
metadata:
  name: {{ include "login.fullname" . }}-wrapper
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "login.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.wrapper.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "login.fullname" . }}-wrapper
