"""
Django settings for manager project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get_docker_secret(
    name,
    default=None,
    secrets_dir=os.path.join(os.path.abspath(os.sep), "app", "secrets"),
):
    value = None

    try:
        with open(os.path.join(secrets_dir, name), "r") as secret_file:
            value = secret_file.read().strip()
    except IOError:
        value = os.environ.get(name.upper())

    # set default value if no value found
    if value is None:
        value = default

    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_docker_secret("django")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [os.environ["DOMAIN"]]


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "request_logging.middleware.LoggingMiddleware",
]

ROOT_URLCONF = "register.urls"

WSGI_APPLICATION = "register.wsgi.application"

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = "/static/"


#####
SESSION_COOKIE_AGE = 5 * 60 * 60
SECURE_PROXY_SSL_HEADER = ("HTTP_" + "HAPROXY_X_FORWARDED_PROTO", "https")
#                                    ^ this value is from gateway/haproxy.conf. Weird I know.

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler", "level": "DEBUG"}},
    "loggers": {
        "django": {"handlers": ["console"], "level": "DEBUG", "propagate": True},
        "register": {"handlers": ["console"], "level": "DEBUG", "propagate": True},
    },
}
