name: Build Web3Modal

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install truffle
        run: |
          npm install -g truffle --unsafe-perm
      - name: Build library
        run: |
          echo "SKIP_PREFLIGHT_CHECK=true" > .env
          npm run bootstrap
          npm run build
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=5120
      - name: Build example
        run: |
          echo "SKIP_PREFLIGHT_CHECK=true" > example/.env
          npm run build:example
        env:
          NODE_OPTIONS: --max_old_space_size=5120
