name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Needs to match "domain" value in values.ci.yaml
  DOMAIN: login.cryptoverse.local
  PROJECT: cryptoverse-login
  REGISTRY: registry.digitalocean.com/cryptoverse

jobs:
  build-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: login/gateway
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.PROJECT }}/gateway:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: login/login
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.PROJECT }}/login:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: login/wrapper
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.PROJECT }}/wrapper:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  test:
    runs-on: ubuntu-latest
    needs:
      - build-gateway
      - build-login
      - build-wrapper
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - uses: balchua/microk8s-actions@v0.2.2
        with:
          channel: "latest/stable"
          addons: '["dns", "ingress"]'
      - name: Create namespace
        run: |
          kubectl create namespace cryptoverse-login-${{ github.sha }}
          kubectl create namespace selenium-grid
      - name: Log in to DO Container Registry
        run: |
          doctl registry login --expiry-seconds 1200
          doctl registry kubernetes-manifest --namespace cryptoverse-login-${{ github.sha }} | kubectl apply -f -
      - name: Resolve domain to localhost #TODO resolve to cluster ip
        run: |
          echo "127.0.0.1 ${DOMAIN}" | sudo tee -a /etc/hosts
      - name: Certs
        run: |
          openssl req -x509 -nodes -days 1 -newkey rsa:2048 \
            -out local.crt \
            -keyout local.key \
            -subj "/CN=${DOMAIN}/O=Cryptoverse OU"
          sudo cp local.crt /etc/ssl/certs/
          sudo update-ca-certificates
          kubectl create secret tls cryptoverse-login \
            --namespace default \
            --key local.key \
            --cert local.crt
          sleep 10s
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Helm install
        run: |
          helm upgrade --install \
            cryptoverse-login \
            ./charts/login/ \
            --namespace cryptoverse-login-${{ github.sha }} \
            -f ./charts/login/values.ci.yaml \
            --set version=${{ github.sha }}
          sleep 2m
      - name: Helm verify
        run: helm list --all-namespaces
      - name: Ingress
        run: |
          kubectl get ingress --all-namespaces
          kubectl describe ingress --all-namespaces
          kubectl describe pod -l name=nginx-ingress-microk8s -n ingress
          kubectl logs -l name=nginx-ingress-microk8s -n ingress
      - name: Services
        run: |
          kubectl get service --all-namespaces
      - name: Pods
        run: |
          kubectl get pods --all-namespaces -o wide --show-labels
      - name: Install Selenium Grid
        run: |
          git clone https://github.com/seleniumhq/docker-selenium.git
          sleep 2m
          helm upgrade --install --wait --timeout 10m \
            --namespace selenium-grid \
            selenium-grid \
            docker-selenium/chart/selenium-grid/. \
            --set chromeNode.enabled=false,edgeNode.enabled=false
      - name: Helm verify \#2
        run: helm list --all-namespaces
      - name: Verify connectivity
        run: |
          curl https://${DOMAIN}/.well-known/openid-configuration -vk
