name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Build
        run: ./docker-build ${{ github.sha }}
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: "latest/stable"
          addons: '["dns", "registry", "prometheus", "ingress"]'
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Create namespace
        run: kubectl create namespace cryptoverse-login-${{ github.sha }}
      - name: Helm install
        run: |
          helm upgrade --install \
            cryptoverse-login \
            ./charts/login/ \
            --namespace cryptoverse-login-${{ github.sha }} \
            -f ./charts/login/values.ci.yaml \
            --set version=${{ github.sha }}
      - name: Helm verify
        run: helm list --all-namespaces
      - name: Logs
        run: kubectl logs -n cryptoverse-login-${{ github.sha }} -l app.kubernetes.io/name=cryptoverse-login -f
      - name: Install Selenium Grid
        run: |
          git clone https://github.com/seleniumhq/docker-selenium.git
          helm upgrade --install \
            selenium-grid \
            docker-selenium/chart/selenium-grid/.
      - name: Helm verify \#2
        run: helm list --all-namespaces
