name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Needs to match "domain" value in values.ci.yaml
  DOMAIN: login.cryptoverse.local
  DOMAIN_DEMO: login-demo.cryptoverse.local
  PROJECT: cryptoverse-login
  REGISTRY: registry.digitalocean.com/cryptoverse

jobs:
  build-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: login/gateway
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.PROJECT }}/gateway:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: login/login
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.PROJECT }}/login:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: login/wrapper
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.PROJECT }}/wrapper:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: test/cryptoverse-login-demo
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.PROJECT }}/demo-python-django:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
  test:
    runs-on: ubuntu-latest
    needs:
      - build-gateway
      - build-login
      - build-wrapper
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - uses: balchua/microk8s-actions@v0.2.2
        with:
          channel: "latest/stable"
          addons: '["dns", "ingress"]'
      - name: Log in to DO Container Registry
        run: |
          doctl registry login --expiry-seconds 1200
          doctl registry kubernetes-manifest --namespace cryptoverse-login-${{ github.sha }} | kubectl apply -f -
      - name: Create Namespace For "Cryptoverse Login"
        run: |
          kubectl create namespace cryptoverse-login-${{ github.sha }}
      - name: Resolve domain to localhost #TODO resolve to cluster ip
        run: |
          echo "127.0.0.1 ${DOMAIN}" | sudo tee -a /etc/hosts
      - name: Certs
        run: |
          openssl req -x509 -nodes -days 1 -newkey rsa:2048 \
            -out local.crt \
            -keyout local.key \
            -subj "/CN=${DOMAIN}/O=Cryptoverse OU"
          sudo cp local.crt /etc/ssl/certs/
          sudo update-ca-certificates
          kubectl create secret tls cryptoverse-login \
            --namespace default \
            --key local.key \
            --cert local.crt
          sleep 10s
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Install Cryptoverse Login
        run: |
          helm upgrade --install --wait --timeout 10m \
            cryptoverse-login \
            ./charts/login/ \
            --namespace cryptoverse-login-${{ github.sha }} \
            -f ./charts/login/values.ci.yaml \
            --set version=${{ github.sha }}
      # - name: Ingress
      #   run: |
      #     kubectl get ingress --all-namespaces
      #     kubectl describe ingress --all-namespaces
      #     kubectl describe pod -l name=nginx-ingress-microk8s -n ingress
      #     kubectl logs -l name=nginx-ingress-microk8s -n ingress
      # - name: Services
      #   run: |
      #     kubectl get service --all-namespaces
      # - name: Pods
      #   run: |
      #     kubectl get pods --all-namespaces -o wide --show-labels
      #     kubectl logs -l app=cryptoverse-login-login
      - name: Verify connectivity
        run: |
          curl https://${DOMAIN}/.well-known/openid-configuration -vk

      ########
      # Demo #
      ########
      - name: Create Namespace For "Cryptoverse Login" Demo App
        run: |
          kubectl create namespace cryptoverse-login-demo-${{ github.sha }}
      - name: Resolve demo app domain to localhost #TODO resolve to cluster ip
        run: |
          echo "127.0.0.1 ${DOMAIN_DEMO}" | sudo tee -a /etc/hosts
      - name: Certs
        run: |
          openssl req -x509 -nodes -days 1 -newkey rsa:2048 \
            -out local-demo.crt \
            -keyout local-demo.key \
            -subj "/CN=${DOMAIN_DEMO}/O=Cryptoverse OU"
          sudo cp local-demo.crt /etc/ssl/certs/
          sudo update-ca-certificates
          kubectl create secret tls cryptoverse-login-demo-python-ingress-tls \
            --namespace default \
            --key local-demo.key \
            --cert local-demo.crt
          sleep 10s
      - name: Install Cryptoverse Login Demo App (Python+Django)
        run: |
          helm upgrade --install --wait --timeout 10m \
            cryptoverse-login-demo \
            ./tests/cryptoverse-login-demo/charts/demo/ \
            --namespace cryptoverse-login-demo-${{ github.sha }} \
            -f ./charts/demo/values.ci.yaml \
            --set version=${{ github.sha }}
            --set demo.secret=SOME_SECRET_HERE
      - name: Ingress
        run: |
          kubectl get ingress --all-namespaces
          kubectl describe ingress --all-namespaces
          kubectl describe pod -l name=nginx-ingress-microk8s -n ingress
          kubectl logs -l name=nginx-ingress-microk8s -n ingress
      - name: Services
        run: |
          kubectl get service --all-namespaces
      - name: Pods
        run: |
          kubectl get pods --all-namespaces -o wide --show-labels
          kubectl logs -l app=cryptoverse-login-login
      # TODO: Test dynamic client registration
      #######################
      # Test using Demo App #
      #######################
      - name: Selenium Tests
        run: |
          cd tests
          pip install -r requirements.txt
          python browser.py -k TestFirefox
