name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install utils
        run: cargo install semver-cli
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Build
        run: ./docker-build ${{ github.sha }}
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: "v1.24.0"
          kubernetes version: "v1.22.0"
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Install Dependencies
        run: |
          minikube addons enable ingress
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install prometheus bitnami/kube-prometheus
      - name: Create namespace
        run: kubectl create namespace cryptoverse-login
      - name: Helm install
        run: helm install cryptoverse-login ./charts/login/ --namespace cryptoverse-login -f ./charts/login/values.ci.yaml
      - name: Helm verify
        run: helm list --all-namespaces
